### ISSUE TITLE
Crear Tabla Proveedores

### ISSUE THREAD

**Issue by bapinedam19** [bapinedam19/ProyectoJKBEAUTY#10]

**Comment by Juanmadrid21** [comment]
CREATE TABLE proveedores(
cod_proveedor int IDENTITY(1,1) not null PRIMARY KEY,
nom_proveedor nvarchar(80) not null,
direccion_proveedor nvarchar(80) not null,
tel_propietario int not null,
correo_proveedor nvarchar(80),
productos_proveedor nvarchar(80)
)
