### ISSUE TITLE
Programación del Botón Exportacion

### ISSUE THREAD

**Issue by bapinedam19** [bapinedam19/ProyectoJKBEAUTY#22]

**Comment by Juanmadrid21** [comment]
private void BFB_Exportar_Click(object sender, EventArgs e)
        {
            exportaraexcel(DGV_Marca);
        }
        public void exportaraexcel(DataGridView DGV_Marca)
        {

            Microsoft.Office.Interop.Excel.Application excel = new Microsoft.Office.Interop.Excel.Application();

            excel.Application.Workbooks.Add(true);

            int IndiceColumna = 0;

            foreach (DataGridViewColumn col in DGV_Marca.Columns) // Columnas
            {

                IndiceColumna++;

                excel.Cells[1, IndiceColumna] = col.Name;

            }

            int IndeceFila = 0;

            foreach (DataGridViewRow row in DGV_Marca.Rows) // Filas
            {

                IndeceFila++;

                IndiceColumna = 0;

                foreach (DataGridViewColumn col in DGV_Marca.Columns)
                {

                    IndiceColumna++;

                    excel.Cells[IndeceFila + 1, IndiceColumna] = row.Cells[col.Name].Value;

                }

            }

            excel.Visible = true;


        }
