### ISSUE TITLE
Scrip de llenado de Factura

### ISSUE THREAD

**Issue by bapinedam19** [bapinedam19/ProyectoJKBEAUTY#28]

**Comment by AngieGarache23** [comment]
INSERT [dbo].[Factura] ([idfactura], [IDEmpleado], [Id_cliente], [impuesto],[metodo_pago]) VALUES (1, 2, 1, 15 ,N'Tarjeta de Credito')
INSERT [dbo].[Factura] ([idfactura], [IDEmpleado], [Id_cliente], [impuesto],[metodo_pago]) VALUES (2, 2, 2, 15 ,N'Contado')
INSERT [dbo].[Factura] ([idfactura], [IDEmpleado], [Id_cliente], [impuesto],[metodo_pago]) VALUES (3, 1, 3, 15 ,N'Tarjeta de Credito')
INSERT [dbo].[Factura] ([idfactura], [IDEmpleado], [Id_cliente], [impuesto],[metodo_pago]) VALUES (4, 1, 4, 15 ,N'Contado')
